#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d 1 2 3
bspc monitor HDMI-1 -d 4 5 6

bspc config border_width         2
bspc config window_gap           0

bspc config presel_feedback_color "#282A2E"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
bspc config single_monocle 	 false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
